const object = [
    {
      gameMaxSize: 50,
      games: [
        {
          czCode: "pgn",
          forwardUrl: "/third/forwardPgn.do?mobile=1&gameType=126&isApp=1",
          gameTabType: 10,
          gameType: "pgn",
          imgUrl: "/common/third/images/egame/pg/v2/126_en.png",
          isListGame: 0,
          lapisId: "pgn",
          moduleCode: 1,
          name: "Fortune Tiger",
          popFrame: false,
          sort: 1000,
        },
        {
          czCode: "pgn",
          forwardUrl: "/third/forwardPgn.do?mobile=1&gameType=1543462&isApp=1",
          gameTabType: 10,
          gameType: "pgn",
          imgUrl: "/common/third/images/egame/pg/v2/1543462_en.png",
          isListGame: 0,
          lapisId: "pgn",
          moduleCode: 1,
          name: "Fortune Rabbit",
          popFrame: false,
          sort: 999,
        },
        {
          czCode: "pgn",
          forwardUrl: "/third/forwardPgn.do?mobile=1&gameType=98&isApp=1",
          gameTabType: 10,
          gameType: "pgn",
          imgUrl: "/common/third/images/egame/pg/v2/98_en.png",
          isListGame: 0,
          lapisId: "pgn",
          moduleCode: 1,
          name: "Fortune Ox",
          popFrame: false,
          sort: 998,
        },
        {
          czCode: "pgn",
          forwardUrl: "/third/forwardPgn.do?mobile=1&gameType=68&isApp=1",
          gameTabType: 10,
          gameType: "pgn",
          imgUrl: "/common/third/images/egame/pg/v2/68_en.png",
          isListGame: 0,
          lapisId: "pgn",
          moduleCode: 1,
          name: "Fortune Mouse",
          popFrame: false,
          sort: 997,
        },
        {
          czCode: "pgn",
          forwardUrl: "/third/forwardPgn.do?mobile=1&gameType=57&isApp=1",
          gameTabType: 10,
          gameType: "pgn",
          imgUrl: "/common/third/images/egame/pg/v2/57_en.png",
          isListGame: 0,
          lapisId: "pgn",
          moduleCode: 1,
          name: "Dragon Hatch",
          popFrame: false,
          sort: 996,
        },
        {
          czCode: "jl",
          forwardUrl: "/third/forwardJl.do?mobile=1&gameType=109&isApp=1",
          gameTabType: 10,
          gameType: "jl",
          imgUrl: "/common/third/images/egame/jl/v4/GAMEID_109_EN.png",
          isListGame: 0,
          lapisId: "jl",
          moduleCode: 1,
          name: "FortuneGems",
          popFrame: false,
          sort: 995,
        },
        {
          czCode: "pgn",
          forwardUrl: "/third/forwardPgn.do?mobile=1&gameType=89&isApp=1",
          gameTabType: 10,
          gameType: "pgn",
          imgUrl: "/common/third/images/egame/pg/v2/89_en.png",
          isListGame: 0,
          lapisId: "pgn",
          moduleCode: 1,
          name: "Lucky Neko",
          popFrame: false,
          sort: 994,
        },
        {
          czCode: "pgn",
          forwardUrl: "/third/forwardPgn.do?mobile=1&gameType=104&isApp=1",
          gameTabType: 10,
          gameType: "pgn",
          imgUrl: "/common/third/images/egame/pg/v2/104_en.png",
          isListGame: 0,
          lapisId: "pgn",
          moduleCode: 1,
          name: "Wild Bandito",
          popFrame: false,
          sort: 993,
        },
        {
          czCode: "pgn",
          forwardUrl: "/third/forwardPgn.do?mobile=1&gameType=42&isApp=1",
          gameTabType: 10,
          gameType: "pgn",
          imgUrl: "/common/third/images/egame/pg/v2/42_en.png",
          isListGame: 0,
          lapisId: "pgn",
          moduleCode: 1,
          name: "Ganesha Gold",
          popFrame: false,
          sort: 992,
        },
        {
          czCode: "pgn",
          forwardUrl: "/third/forwardPgn.do?mobile=1&gameType=48&isApp=1",
          gameTabType: 10,
          gameType: "pgn",
          imgUrl: "/common/third/images/egame/pg/v2/48_en.png",
          isListGame: 0,
          lapisId: "pgn",
          moduleCode: 1,
          name: "Double Fortune",
          popFrame: false,
          sort: 991,
        },
        {
          czCode: "pp",
          forwardUrl:
            "/third/forwardPP.do?mobile=1&gameType=vs20olympgate&isApp=1",
          gameTabType: 10,
          gameType: "pp",
          imgUrl: "/common/third/images/egame/pp/v4/GatesofOlympus.png",
          isListGame: 0,
          lapisId: "pp",
          moduleCode: 1,
          name: "Gates of Olympus",
          popFrame: false,
          sort: 990,
        },
        {
          czCode: "pgn",
          forwardUrl: "/third/forwardPgn.do?mobile=1&gameType=1402846&isApp=1",
          gameTabType: 10,
          gameType: "pgn",
          imgUrl: "/common/third/images/egame/pg/v2/1402846_en.png",
          isListGame: 0,
          lapisId: "pgn",
          moduleCode: 1,
          name: "Midas Fortune",
          popFrame: false,
          sort: 989,
        },
        {
          czCode: "pgn",
          forwardUrl: "/third/forwardPgn.do?mobile=1&gameType=39&isApp=1",
          gameTabType: 10,
          gameType: "pgn",
          imgUrl: "/common/third/images/egame/pg/v2/39_en.png",
          isListGame: 0,
          lapisId: "pgn",
          moduleCode: 1,
          name: "Pig Gold",
          popFrame: false,
          sort: 988,
        },
        {
          czCode: "pgn",
          forwardUrl: "/third/forwardPgn.do?mobile=1&gameType=40&isApp=1",
          gameTabType: 10,
          gameType: "pgn",
          imgUrl: "/common/third/images/egame/pg/v2/40_en.png",
          isListGame: 0,
          lapisId: "pgn",
          moduleCode: 1,
          name: "Jungle Delight",
          popFrame: false,
          sort: 987,
        },
        {
          czCode: "pgn",
          forwardUrl: "/third/forwardPgn.do?mobile=1&gameType=63&isApp=1",
          gameTabType: 10,
          gameType: "pgn",
          imgUrl: "/common/third/images/egame/pg/v2/63_en.png",
          isListGame: 0,
          lapisId: "pgn",
          moduleCode: 1,
          name: "Dragon Tiger Luck",
          popFrame: false,
          sort: 986,
        },
        {
          czCode: "pgn",
          forwardUrl: "/third/forwardPgn.do?mobile=1&gameType=53&isApp=1",
          gameTabType: 10,
          gameType: "pgn",
          imgUrl: "/common/third/images/egame/pg/v2/53_en.png",
          isListGame: 0,
          lapisId: "pgn",
          moduleCode: 1,
          name: "The Great Icescape",
          popFrame: false,
          sort: 985,
        },
        {
          czCode: "pg",
          forwardUrl: "/third/forwardPg2.do?mobile=1&gameType=71&isApp=1",
          gameTabType: 10,
          gameType: "pg",
          imgUrl: "/common/third/images/egame/pg/v2/71_en.png",
          isListGame: 0,
          lapisId: "pg",
          moduleCode: 1,
          name: "Caishen Wins",
          popFrame: false,
          sort: 984,
        },
        {
          czCode: "pgn",
          forwardUrl: "/third/forwardPgn.do?mobile=1&gameType=75&isApp=1",
          gameTabType: 10,
          gameType: "pgn",
          imgUrl: "/common/third/images/egame/pg/v2/75_en.png",
          isListGame: 0,
          lapisId: "pgn",
          moduleCode: 1,
          name: "Ganesha Fortune",
          popFrame: false,
          sort: 983,
        },
        {
          czCode: "jl",
          forwardUrl: "/third/forwardJl.do?mobile=1&gameType=51&isApp=1",
          gameTabType: 10,
          gameType: "jl",
          imgUrl: "/common/third/images/egame/jl/v4/GAMEID_51_EN.png",
          isListGame: 0,
          lapisId: "jl",
          moduleCode: 1,
          name: "MoneyComing",
          popFrame: false,
          sort: 982,
        },
        {
          czCode: "pg",
          forwardUrl: "/third/forwardPg2.do?mobile=1&gameType=84&isApp=1",
          gameTabType: 10,
          gameType: "pg",
          imgUrl: "/common/third/images/egame/pg/v2/84_en.png",
          isListGame: 0,
          lapisId: "pg",
          moduleCode: 1,
          name: "Queen of Bounty",
          popFrame: false,
          sort: 981,
        },
        {
          czCode: "pgn",
          forwardUrl: "/third/forwardPgn.do?mobile=1&gameType=135&isApp=1",
          gameTabType: 10,
          gameType: "pgn",
          imgUrl: "/common/third/images/egame/pg/v2/135_en.png",
          isListGame: 0,
          lapisId: "pgn",
          moduleCode: 1,
          name: "Wild Bounty Showdown",
          popFrame: false,
          sort: 980,
        },
        {
          czCode: "pgn",
          forwardUrl: "/third/forwardPgn.do?mobile=1&gameType=117&isApp=1",
          gameTabType: 10,
          gameType: "pgn",
          imgUrl: "/common/third/images/egame/pg/v2/117_en.png",
          isListGame: 0,
          lapisId: "pgn",
          moduleCode: 1,
          name: "Cocktail Nights",
          popFrame: false,
          sort: 979,
        },
        {
          czCode: "pgn",
          forwardUrl: "/third/forwardPgn.do?mobile=1&gameType=115&isApp=1",
          gameTabType: 10,
          gameType: "pgn",
          imgUrl: "/common/third/images/egame/pg/v2/115_en.png",
          isListGame: 0,
          lapisId: "pgn",
          moduleCode: 1,
          name: "Supermarket Spree",
          popFrame: false,
          sort: 978,
        },
        {
          czCode: "pgn",
          forwardUrl: "/third/forwardPgn.do?mobile=1&gameType=130&isApp=1",
          gameTabType: 10,
          gameType: "pgn",
          imgUrl: "/common/third/images/egame/pg/v2/130_en.png",
          isListGame: 0,
          lapisId: "pgn",
          moduleCode: 1,
          name: "Lucky Piggy",
          popFrame: false,
          sort: 977,
        },
        {
          czCode: "pp",
          forwardUrl:
            "/third/forwardPP.do?mobile=1&gameType=vs20sugarrush&isApp=1",
          gameTabType: 10,
          gameType: "pp",
          imgUrl: "/common/third/images/egame/pp/v4/SugarRush.png",
          isListGame: 0,
          lapisId: "pp",
          moduleCode: 1,
          name: "Sugar Rush",
          popFrame: false,
          sort: 976,
        },
        {
          czCode: "pp",
          forwardUrl:
            "/third/forwardPP.do?mobile=1&gameType=vs20fruitparty&isApp=1",
          gameTabType: 10,
          gameType: "pp",
          imgUrl: "/common/third/images/egame/pp/v4/FruitParty.png",
          isListGame: 0,
          lapisId: "pp",
          moduleCode: 1,
          name: "Fruit Party",
          popFrame: false,
          sort: 975,
        },
        {
          czCode: "pp",
          forwardUrl: "/third/forwardPP.do?mobile=1&gameType=1301&isApp=1",
          gameTabType: 10,
          gameType: "pp",
          imgUrl: "/common/third/images/egame/pp/v4/Spaceman.png",
          isListGame: 0,
          lapisId: "pp",
          moduleCode: 1,
          name: "Spaceman",
          popFrame: false,
          sort: 974,
        },
        {
          czCode: "jl",
          forwardUrl: "/third/forwardJl.do?mobile=1&gameType=47&isApp=1",
          gameTabType: 10,
          gameType: "jl",
          imgUrl: "/common/third/images/egame/jl/v4/GAMEID_47_EN.png",
          isListGame: 0,
          lapisId: "jl",
          moduleCode: 1,
          name: "Charge Buffalo",
          popFrame: false,
          sort: 973,
        },
        {
          czCode: "pgn",
          forwardUrl: "/third/forwardPgn.do?mobile=1&gameType=74&isApp=1",
          gameTabType: 10,
          gameType: "pgn",
          imgUrl: "/common/third/images/egame/pg/v2/74_en.png",
          isListGame: 0,
          lapisId: "pgn",
          moduleCode: 1,
          name: "Mahjong Ways 2",
          popFrame: false,
          sort: 971,
        },
        {
          czCode: "pgn",
          forwardUrl: "/third/forwardPgn.do?mobile=1&gameType=54&isApp=1",
          gameTabType: 10,
          gameType: "pgn",
          imgUrl: "/common/third/images/egame/pg/v2/54_en.png",
          isListGame: 0,
          lapisId: "pgn",
          moduleCode: 1,
          name: "Captains Bounty",
          popFrame: false,
          sort: 970,
        },
        {
          czCode: "jl",
          forwardUrl: "/third/forwardJl.do?mobile=1&gameType=35&isApp=1",
          gameTabType: 10,
          gameType: "jl",
          imgUrl: "/common/third/images/egame/jl/v4/GAMEID_35_EN.png",
          isListGame: 0,
          lapisId: "jl",
          moduleCode: 1,
          name: "Crazy777",
          popFrame: false,
          sort: 969,
        },
        {
          czCode: "pgn",
          forwardUrl: "/third/forwardPgn.do?mobile=1&gameType=87&isApp=1",
          gameTabType: 10,
          gameType: "pgn",
          imgUrl: "/common/third/images/egame/pg/v2/87_en.png",
          isListGame: 0,
          lapisId: "pgn",
          moduleCode: 1,
          name: "Treasures Aztec",
          popFrame: false,
          sort: 968,
        },
        {
          czCode: "jl",
          forwardUrl: "/third/forwardJl.do?mobile=1&gameType=6&isApp=1",
          gameTabType: 10,
          gameType: "jl",
          imgUrl: "/common/third/images/egame/jl/v4/GAMEID_6_EN.png",
          isListGame: 0,
          lapisId: "jl",
          moduleCode: 1,
          name: "fortune tree",
          popFrame: false,
          sort: 967,
        },
        {
          czCode: "pgn",
          forwardUrl: "/third/forwardPgn.do?mobile=1&gameType=80&isApp=1",
          gameTabType: 10,
          gameType: "pgn",
          imgUrl: "/common/third/images/egame/pg/v2/80_en.png",
          isListGame: 0,
          lapisId: "pgn",
          moduleCode: 1,
          name: "Circus Delight",
          popFrame: false,
          sort: 966,
        },
        {
          czCode: "pgn",
          forwardUrl: "/third/forwardPgn.do?mobile=1&gameType=110&isApp=1",
          gameTabType: 10,
          gameType: "pgn",
          imgUrl: "/common/third/images/egame/pg/v2/110_en.png",
          isListGame: 0,
          lapisId: "pgn",
          moduleCode: 1,
          name: "Jurassic Kingdom",
          popFrame: false,
          sort: 965,
        },
        {
          czCode: "pgn",
          forwardUrl: "/third/forwardPgn.do?mobile=1&gameType=127&isApp=1",
          gameTabType: 10,
          gameType: "pgn",
          imgUrl: "/common/third/images/egame/pg/v2/127_en.png",
          isListGame: 0,
          lapisId: "pgn",
          moduleCode: 1,
          name: "Speed Winner",
          popFrame: false,
          sort: 964,
        },
        {
          czCode: "jl",
          forwardUrl: "/third/forwardJl.do?mobile=1&gameType=58&isApp=1",
          gameTabType: 10,
          gameType: "jl",
          imgUrl: "/common/third/images/egame/jl/v4/GAMEID_58_EN.png",
          isListGame: 0,
          lapisId: "jl",
          moduleCode: 1,
          name: "GoldenQueen",
          popFrame: false,
          sort: 963,
        },
      ],
      tab: {
        code: "hotgame_tab_icon",
        createTime: 1712902724314,
        customTitle: "",
        icon: "",
        id: 129,
        index: 0,
        name: "Hot Games",
        selectedIcon: "",
        sortNo: 2,
        stationId: 6,
        status: 2,
        type: 10,
      },
    },
    {
      gameMaxSize: 50,
      games: [
        {
          czCode: "pg",
          feeConvertUrl: "/thirdTrans/thirdRealTransMoney.do",
          forwardUrl: "/third/forwardPg2.do?mobile=1&isApp=1",
          gameTabType: 2,
          gameType: "pg",
          imgUrl: "/common/third/images/egame/cover-images/v2/slot-pg.png",
          isListGame: 1,
          lapisId: "pg",
          moduleCode: 1,
          name: "Pocket Game Eletrônico",
          popFrame: true,
          type: "3",
        },
        {
          czCode: "pgn",
          feeConvertUrl: "/thirdTrans/thirdRealTransMoney.do",
          forwardUrl: "/third/forwardPgn.do?mobile=1&isApp=1",
          gameTabType: 2,
          gameType: "pgn",
          imgUrl: "/common/third/images/egame/cover-images/v2/slot-pgn.png",
          isListGame: 1,
          lapisId: "pgn",
          moduleCode: 1,
          name: "Pocket Game Eletrônico",
          popFrame: true,
          type: "3",
        },
        {
          czCode: "bs",
          feeConvertUrl: "/thirdTrans/thirdRealTransMoney.do",
          forwardUrl: "/third/forwardEvo.do?mobile=1&isApp=1",
          gameTabType: 2,
          gameType: "bs",
          imgUrl: "/common/third/images/egame/cover-images/v2/slot-bs.png",
          isListGame: 1,
          lapisId: "bs",
          moduleCode: 1,
          name: "BGsoft",
          popFrame: true,
          type: "3",
        },
        {
          czCode: "jdb",
          feeConvertUrl: "/thirdTrans/thirdRealTransMoney.do",
          forwardUrl: "/third/forwardJdb.do?mobile=1&isApp=1",
          gameTabType: 2,
          gameType: "jdb",
          imgUrl: "/common/third/images/egame/cover-images/v2/slot-jdb.png",
          isListGame: 1,
          lapisId: "jdb",
          moduleCode: 1,
          name: "Just Do Best",
          popFrame: true,
          type: "3",
        },
        {
          czCode: "ag",
          feeConvertUrl: "/thirdTrans/thirdRealTransMoney.do",
          forwardUrl: "/third/forwardAg.do?mobile=1&isApp=1",
          gameTabType: 2,
          gameType: "ag",
          imgUrl: "/common/third/images/egame/cover-images/v2/slot-ag.png",
          isListGame: 1,
          lapisId: "ag",
          moduleCode: 1,
          name: "Xin Gaming",
          popFrame: true,
          type: "3",
        },
        {
          czCode: "bbin",
          feeConvertUrl: "/thirdTrans/thirdRealTransMoney.do",
          forwardUrl:
            "/third/forwardBbin2.do?gameType=game&gameId=5000&mobile=1&isApp=1",
          gameTabType: 2,
          gameType: "bbin",
          imgUrl: "/common/third/images/egame/cover-images/v2/slot-bbin.png",
          isListGame: 1,
          lapisId: "bbin",
          moduleCode: 1,
          name: "BB Casino",
          popFrame: true,
          type: "3",
        },
        {
          czCode: "mg",
          feeConvertUrl: "/thirdTrans/thirdRealTransMoney.do",
          forwardUrl: "/third/forwardMg.do?mobile=1&isApp=1",
          gameTabType: 2,
          gameType: "mg",
          imgUrl: "/common/third/images/egame/cover-images/v2/slot-mg.png",
          isListGame: 1,
          lapisId: "mg",
          moduleCode: 1,
          name: "Microgaming",
          popFrame: true,
          type: "3",
        },
        {
          czCode: "cq9",
          feeConvertUrl: "/thirdTrans/thirdRealTransMoney.do",
          forwardUrl: "/third/forwardCq9.do?mobile=1&isApp=1",
          gameTabType: 2,
          gameType: "cq9",
          imgUrl: "/common/third/images/egame/cover-images/v2/slot-cq9.png",
          isListGame: 1,
          lapisId: "cq9",
          moduleCode: 1,
          name: "CQ9",
          popFrame: true,
          type: "3",
        },
        {
          czCode: "evo",
          feeConvertUrl: "/thirdTrans/thirdRealTransMoney.do",
          forwardUrl: "/third/forwardEvo.do?mobile=1&isApp=1",
          gameTabType: 2,
          gameType: "evo",
          imgUrl: "/common/third/images/egame/cover-images/v2/slot-evo.png",
          isListGame: 1,
          lapisId: "evo",
          moduleCode: 1,
          name: "Evoplay",
          popFrame: true,
          type: "3",
        },
        {
          czCode: "fg",
          feeConvertUrl: "/thirdTrans/thirdRealTransMoney.do",
          forwardUrl: "/third/forwardFg.do?mobile=1&isApp=1",
          gameTabType: 2,
          gameType: "fg",
          imgUrl: "/common/third/images/egame/cover-images/v2/slot-fg.png",
          isListGame: 1,
          lapisId: "fg",
          moduleCode: 1,
          name: "FunGaming",
          popFrame: true,
          type: "3",
        },
        {
          czCode: "tada",
          feeConvertUrl: "/thirdTrans/thirdRealTransMoney.do",
          forwardUrl: "/third/forwardTada.do?mobile=1&isApp=1",
          gameTabType: 2,
          gameType: "tada",
          imgUrl: "/common/third/images/egame/cover-images/v2/slot-tada.png",
          isListGame: 1,
          lapisId: "tada",
          moduleCode: 1,
          name: "TADA",
          popFrame: true,
          type: "3",
        },
        {
          czCode: "pp",
          feeConvertUrl: "/thirdTrans/thirdRealTransMoney.do",
          forwardUrl: "/third/forwardPP.do?mobile=1&isApp=1",
          gameTabType: 2,
          gameType: "pp",
          imgUrl: "/common/third/images/egame/cover-images/v2/slot-pp.png",
          isListGame: 1,
          lapisId: "pp",
          moduleCode: 1,
          name: "Pragmatic Play",
          popFrame: true,
          type: "3",
        },
        {
          czCode: "jl",
          feeConvertUrl: "/thirdTrans/thirdRealTransMoney.do",
          forwardUrl: "/third/forwardJl.do?mobile=1&isApp=1&gameType=1",
          gameTabType: 2,
          gameType: "jl",
          imgUrl: "/common/third/images/egame/cover-images/v2/slot-jl.png",
          isListGame: 1,
          lapisId: "jl",
          moduleCode: 1,
          name: "JILI",
          popFrame: true,
          type: "3",
        },
        {
          czCode: "es",
          feeConvertUrl: "/thirdTrans/thirdRealTransMoney.do",
          forwardUrl: "/third/forwardEs.do?mobile=1&isApp=1",
          gameTabType: 2,
          gameType: "es",
          imgUrl: "/common/third/images/egame/cover-images/v2/slot-es.png",
          isListGame: 1,
          lapisId: "es",
          moduleCode: 1,
          name: "ES",
          popFrame: true,
          type: "3",
        },
      ],
      tab: {
        code: "dianzi_tab_icon",
        createTime: 1709308745122,
        customTitle: "",
        icon: "",
        id: 124,
        index: 1,
        name: "电子",
        selectedIcon: "",
        sortNo: 3,
        stationId: 6,
        status: 2,
        type: 2,
      },
    },
    {
      gameMaxSize: 50,
      games: [
        {
          czCode: "bbinFish",
          feeConvertUrl: "/thirdTrans/thirdRealTransMoney.do",
          forwardUrl:
            "/third/forwardBbin2.do?gameType=bigfish_38001&mobile=1&isApp=1",
          gameTabType: 7,
          gameType: "bbinFish",
          imgUrl: "/common/third/images/fish/cover-images/v2/fish-bbin.png",
          isListGame: 1,
          lapisId: "bbinFish",
          moduleCode: 1,
          name: "BBIN Salão de jogos de Pescaria",
          popFrame: true,
          type: "6",
        },
        {
          czCode: "cq9Fish",
          feeConvertUrl: "/thirdTrans/thirdRealTransMoney.do",
          forwardUrl: "/third/forwardCq9.do?mobile=1&isApp=1",
          gameTabType: 7,
          gameType: "cq9Fish",
          imgUrl: "/common/third/images/fish/cover-images/v2/fish-cq9.png",
          isListGame: 1,
          lapisId: "cq9Fish",
          moduleCode: 1,
          name: "Jogo de pesca CQ9",
          popFrame: true,
          type: "6",
        },
      ],
      tab: {
        code: "duyu_tab_icon",
        createTime: 1711366038394,
        customTitle: "",
        icon: "",
        id: 127,
        index: 2,
        name: "Fishing",
        selectedIcon: "",
        sortNo: 4,
        stationId: 6,
        status: 2,
        type: 7,
      },
    },
    {
      gameMaxSize: 50,
      games: [
        {
          czCode: "tysbSport",
          feeConvertUrl: "/thirdTrans/thirdRealTransMoney.do",
          forwardUrl: "/third/forwardTysb.do?mobile=1&isApp=1",
          gameTabType: 0,
          gameType: "tysbSport",
          imgUrl: "/common/third/images/sport/cover-images/v2/sport-saba.png",
          isListGame: 1,
          lapisId: "tysbSport",
          moduleCode: 1,
          name: "Sabah Esportes",
          popFrame: true,
          type: "4",
        },
        {
          czCode: "ppSport",
          feeConvertUrl: "/thirdTrans/thirdRealTransMoney.do",
          forwardUrl: "/third/forwardPP.do?mobile=1&isApp=1&gameType=sport",
          gameTabType: 0,
          gameType: "ppSport",
          imgUrl: "/common/third/images/sport/cover-images/v2/sport-pp.png",
          isListGame: 1,
          lapisId: "ppSport",
          moduleCode: 1,
          name: "Pragmatic Play Esportes",
          popFrame: true,
          type: "4",
        },
        {
          czCode: "fb",
          feeConvertUrl: "/thirdTrans/thirdRealTransMoney.do",
          forwardUrl: "/third/forwardFB.do?mobile=1&isApp=1&gameType=sport",
          gameTabType: 0,
          gameType: "fb",
          imgUrl: "/common/third/images/sport/cover-images/v2/sport-fb.png",
          isListGame: 1,
          lapisId: "fb",
          moduleCode: 1,
          name: "FB Esportes",
          popFrame: true,
          type: "4",
        },
      ],
      tab: {
        code: "sport_tab_icon",
        createTime: 1709308732520,
        customTitle: "",
        icon: "",
        id: 125,
        index: 3,
        name: "体育",
        selectedIcon: "",
        sortNo: 5,
        stationId: 6,
        status: 2,
        type: 0,
      },
    },
    {
      gameMaxSize: 50,
      games: [
        {
          czCode: "agLive",
          feeConvertUrl: "/thirdTrans/thirdRealTransMoney.do",
          forwardUrl: "/third/forwardAg.do?mobile=1&isApp=1",
          gameTabType: 1,
          gameType: "agLive",
          imgUrl: "/common/third/images/live/cover-images/v2/live-ag.png",
          isListGame: 1,
          lapisId: "agLive",
          moduleCode: 1,
          name: "Asia Gaming(Salão da atriz)",
          popFrame: true,
          type: "2",
        },
        {
          czCode: "bbinLive",
          feeConvertUrl: "/thirdTrans/thirdRealTransMoney.do",
          forwardUrl: "/third/forwardBbin2.do?gameType=live&mobile=1&isApp=1",
          gameTabType: 1,
          gameType: "bbinLive",
          imgUrl: "/common/third/images/live/cover-images/v2/live-bbin.png",
          isListGame: 1,
          lapisId: "bbinLive",
          moduleCode: 1,
          name: "BB Live(Salão de Taiwan)",
          popFrame: true,
          type: "2",
        },
        {
          czCode: "mgLive",
          feeConvertUrl: "/thirdTrans/thirdRealTransMoney.do",
          forwardUrl: "/third/forwardMg.do?gameType=1210&mobile=1&isApp=1",
          gameTabType: 1,
          gameType: "mgLive",
          imgUrl: "/common/third/images/live/cover-images/v2/live-mg.png",
          isListGame: 1,
          lapisId: "mgLive",
          moduleCode: 1,
          name: "Microgaming(Salão Europeu e Americano)",
          popFrame: true,
          type: "2",
        },
        {
          czCode: "dgLive",
          feeConvertUrl: "/thirdTrans/thirdRealTransMoney.do",
          forwardUrl: "/third/forwardDg.do?mobile=1&isApp=1",
          gameTabType: 1,
          gameType: "dgLive",
          imgUrl: "/common/third/images/live/cover-images/v2/live-dg.png",
          isListGame: 1,
          lapisId: "dgLive",
          moduleCode: 1,
          name: "DG",
          popFrame: true,
          type: "2",
        },
        {
          czCode: "evolution",
          feeConvertUrl: "/thirdTrans/thirdRealTransMoney.do",
          forwardUrl: "/third/forwardEvolution.do?mobile=1&isApp=1",
          gameTabType: 1,
          gameType: "evolution",
          imgUrl:
            "/common/third/images/live/cover-images/v2/live-evolution.png",
          isListGame: 1,
          lapisId: "evolution",
          moduleCode: 1,
          name: "Evolution",
          popFrame: true,
          type: "2",
        },
        {
          czCode: "ppLive",
          feeConvertUrl: "/thirdTrans/thirdRealTransMoney.do",
          forwardUrl: "/third/forwardPP.do?mobile=1&isApp=1&gameType=live",
          gameTabType: 1,
          gameType: "ppLive",
          imgUrl: "/common/third/images/live/cover-images/v2/live-pp.png",
          isListGame: 1,
          lapisId: "ppLive",
          moduleCode: 1,
          name: "Pragmatic Play",
          popFrame: true,
          type: "2",
        },
        {
          czCode: "awc",
          feeConvertUrl: "/thirdTrans/thirdRealTransMoney.do",
          forwardUrl: "/third/forwardAwc.do?mobile=1&isApp=1&gameType=live",
          gameTabType: 1,
          gameType: "awc",
          imgUrl: "/common/third/images/live/cover-images/v2/live-awc.png",
          isListGame: 1,
          lapisId: "awc",
          moduleCode: 1,
          name: "AWC",
          popFrame: true,
          type: "2",
        },
      ],
      tab: {
        code: "real_tab_icon",
        createTime: 1711366047143,
        customTitle: "",
        icon: "",
        id: 123,
        index: 4,
        name: "真人",
        selectedIcon: "",
        sortNo: 6,
        stationId: 6,
        status: 2,
        type: 1,
      },
    },
    {
      gameMaxSize: 50,
      games: [],
      tab: {
        code: "official_tab_icon",
        createTime: 1712902705209,
        customTitle: "",
        icon: "",
        id: 282,
        index: 5,
        name: "Lottery",
        selectedIcon: "",
        sortNo: 10,
        stationId: 6,
        status: 2,
        type: 3,
      },
    },
  ];

